$Global:ChunkSizeListeners = @()
$Global:DelayMsListeners = @()
$Global:ChunkTransferredListeners = @()
$Global:TransferWrapupListeners = @()
$Global:TransferCompleteListeners = @()
$Global:SetDestinationPathListeners = @()
$Global:SetDestinationFilenameListeners = @()
$Global:SetStatusInformationListeners = @()